name: Meal Plan Updater
on:
  workflow_dispatch: # Manually run workflow when desired
  schedule:
    # Run every Saturday at 3am
    - cron: '0 3 * * 6'

jobs:
  Update-Meal-Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update Meal Plan
        run: python plan_dinners.py
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
